// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gerenciador_De_Projetos.MODEL.Models;

public partial class EQUIPE
{
    public int EqpCodigo { get; set; }

    public string EqpNome { get; set; }

    public bool EqpStatus { get; set; }

    public DateTime EqpDataInicio { get; set; }

    public DateTime? EqpDataFinal { get; set; }

    public virtual ICollection<MEMBRO_EQUIPE> MEMBRO_EQUIPE { get; set; } = new List<MEMBRO_EQUIPE>();

    public virtual ICollection<PROJETO> PROJETO { get; set; } = new List<PROJETO>();
}