// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Gerenciador_De_Projetos.MODEL.Models;

public partial class Gerenciador_De_ProjetosContext : DbContext
{
    public Gerenciador_De_ProjetosContext()
    {
    }

    public Gerenciador_De_ProjetosContext(DbContextOptions<Gerenciador_De_ProjetosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ENDERECO> ENDERECO { get; set; }

    public virtual DbSet<EQUIPE> EQUIPE { get; set; }

    public virtual DbSet<MEMBROS> MEMBROS { get; set; }

    public virtual DbSet<MEMBRO_EQUIPE> MEMBRO_EQUIPE { get; set; }

    public virtual DbSet<PROJETO> PROJETO { get; set; }

    public virtual DbSet<TAREFA> TAREFA { get; set; }

    public virtual DbSet<TIPO_PROJETO> TIPO_PROJETO { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=PC_MARCO_RYAN\\SQLEXPRESS;Initial Catalog=Gerenciador_De_Projetos;Integrated Security=True;Encrypt=True; TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ENDERECO>(entity =>
        {
            entity.HasKey(e => e.EndCodigo).HasName("PK__ENDERECO__4EB6A165BE45F3E0");

            entity.Property(e => e.EndBairro)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EndCEP)
                .IsRequired()
                .HasMaxLength(9)
                .IsUnicode(false);
            entity.Property(e => e.EndCidade)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EndComplemento)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EndLogradouro)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EndPais)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.EndUF)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
        });

        modelBuilder.Entity<EQUIPE>(entity =>
        {
            entity.HasKey(e => e.EqpCodigo).HasName("PK__EQUIPE__0FD232B0ACB4F54D");

            entity.Property(e => e.EqpDataFinal).HasColumnType("datetime");
            entity.Property(e => e.EqpDataInicio).HasColumnType("datetime");
            entity.Property(e => e.EqpNome)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<MEMBROS>(entity =>
        {
            entity.HasKey(e => e.MemCodigo).HasName("PK__MEMBROS__CF337F24D7AFDA0C");

            entity.HasIndex(e => e.EndCodigo, "MEMBROS_FKIndex1");

            entity.Property(e => e.MemCPF)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false);
            entity.Property(e => e.MemDataNascimento).HasColumnType("datetime");
            entity.Property(e => e.MemEmail)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.MemNome)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MemSexo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.MemTelefone)
                .HasMaxLength(14)
                .IsUnicode(false);

            entity.HasOne(d => d.EndCodigoNavigation).WithMany(p => p.MEMBROS)
                .HasForeignKey(d => d.EndCodigo)
                .HasConstraintName("FK__MEMBROS__EndCodi__3E52440B");
        });

        modelBuilder.Entity<MEMBRO_EQUIPE>(entity =>
        {
            entity.HasKey(e => new { e.MeqCodigoMembro, e.MeqCodigoEquipe }).HasName("PK__MEMBRO_E__A9DE3AAFC4B406B4");

            entity.HasIndex(e => e.MeqCodigoEquipe, "MEMBRO_EQUIPE_FKIndex1");

            entity.HasIndex(e => e.MeqCodigoMembro, "MEMBRO_EQUIPE_FKIndex2");

            entity.Property(e => e.MeqDataRegistro).HasColumnType("datetime");
            entity.Property(e => e.MeqFuncao)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.MeqCodigoEquipeNavigation).WithMany(p => p.MEMBRO_EQUIPE)
                .HasForeignKey(d => d.MeqCodigoEquipe)
                .HasConstraintName("FK__MEMBRO_EQ__MeqCo__412EB0B6");

            entity.HasOne(d => d.MeqCodigoMembroNavigation).WithMany(p => p.MEMBRO_EQUIPE)
                .HasForeignKey(d => d.MeqCodigoMembro)
                .HasConstraintName("FK__MEMBRO_EQ__MeqCo__4222D4EF");
        });

        modelBuilder.Entity<PROJETO>(entity =>
        {
            entity.HasKey(e => e.ProjCodigo).HasName("PK__PROJETO__77B7AA322FA41F73");

            entity.HasIndex(e => e.TpPCodigo, "PROJETO_FKIndex1");

            entity.HasIndex(e => e.TarCodigo, "PROJETO_FKIndex2");

            entity.HasIndex(e => e.EqpCodigo, "PROJETO_FKIndex3");

            entity.Property(e => e.ProDataFinal).HasColumnType("datetime");
            entity.Property(e => e.ProDataInicio).HasColumnType("datetime");
            entity.Property(e => e.ProjNome)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.EqpCodigoNavigation).WithMany(p => p.PROJETO)
                .HasForeignKey(d => d.EqpCodigo)
                .HasConstraintName("FK__PROJETO__EqpCodi__46E78A0C");

            entity.HasOne(d => d.TarCodigoNavigation).WithMany(p => p.PROJETO)
                .HasForeignKey(d => d.TarCodigo)
                .HasConstraintName("FK__PROJETO__TarCodi__45F365D3");

            entity.HasOne(d => d.TpPCodigoNavigation).WithMany(p => p.PROJETO)
                .HasForeignKey(d => d.TpPCodigo)
                .HasConstraintName("FK__PROJETO__TpPCodi__44FF419A");
        });

        modelBuilder.Entity<TAREFA>(entity =>
        {
            entity.HasKey(e => e.TarCodigo).HasName("PK__TAREFA__B889E929BD5234C4");

            entity.Property(e => e.TarDataFinal).HasColumnType("datetime");
            entity.Property(e => e.TarDataInicio).HasColumnType("datetime");
            entity.Property(e => e.TarDescricao)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.TarNome)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TIPO_PROJETO>(entity =>
        {
            entity.HasKey(e => e.TpPCodigo).HasName("PK__TIPO_PRO__A9B7F3258966B87B");

            entity.Property(e => e.TpPDescricao)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}