// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Gerenciador_De_Projetos.MODEL.Models;

public partial class Gerenciador_De_ProjetosContext : DbContext
{
    public Gerenciador_De_ProjetosContext()
    {
    }

    public Gerenciador_De_ProjetosContext(DbContextOptions<Gerenciador_De_ProjetosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ENDERECO> ENDERECO { get; set; }

    public virtual DbSet<EQUIPE> EQUIPE { get; set; }

    public virtual DbSet<MEMBROS> MEMBROS { get; set; }

    public virtual DbSet<MEMBRO_EQUIPE> MEMBRO_EQUIPE { get; set; }

    public virtual DbSet<PROJETO> PROJETO { get; set; }

    public virtual DbSet<TAREFA> TAREFA { get; set; }

    public virtual DbSet<TIPO_PROJETO> TIPO_PROJETO { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=PC_MARCO_RYAN\\SQLEXPRESS;Initial Catalog=Gerenciador_De_Projetos;Integrated Security=True;Encrypt=True;TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ENDERECO>(entity =>
        {
            entity.HasKey(e => e.EndCodigo).HasName("PK__ENDERECO__4EB6A165DB45077C");

            entity.HasIndex(e => e.EndCodigoMembro, "ENDERECO_FKIndex1");

            entity.Property(e => e.EndBairro)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EndCEP)
                .IsRequired()
                .HasMaxLength(9)
                .IsUnicode(false);
            entity.Property(e => e.EndCidade)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EndComplemento)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EndLogradouro)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EndPais)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EndUF)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.EndCodigoMembroNavigation).WithMany(p => p.ENDERECO)
                .HasForeignKey(d => d.EndCodigoMembro)
                .HasConstraintName("FK__ENDERECO__EndCod__3A81B327");
        });

        modelBuilder.Entity<EQUIPE>(entity =>
        {
            entity.HasKey(e => e.EqpCodigo).HasName("PK__EQUIPE__0FD232B08ABDE5AC");

            entity.HasIndex(e => e.EqpCodigoProjeto, "EQUIPE_FKIndex1");

            entity.Property(e => e.EqpDataFinal).HasColumnType("datetime");
            entity.Property(e => e.EqpDataInicio).HasColumnType("datetime");
            entity.Property(e => e.EqpNome)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.EqpCodigoProjetoNavigation).WithMany(p => p.EQUIPE)
                .HasForeignKey(d => d.EqpCodigoProjeto)
                .HasConstraintName("FK__EQUIPE__EqpCodig__403A8C7D");
        });

        modelBuilder.Entity<MEMBROS>(entity =>
        {
            entity.HasKey(e => e.MemCodigo).HasName("PK__MEMBROS__CF337F24DE2B3F2D");

            entity.Property(e => e.MemCPF)
                .IsRequired()
                .HasMaxLength(14)
                .IsUnicode(false);
            entity.Property(e => e.MemDataNascimento).HasColumnType("datetime");
            entity.Property(e => e.MemEmail)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.MemNome)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MemSexo)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.MemTelefone)
                .HasMaxLength(14)
                .IsUnicode(false);
        });

        modelBuilder.Entity<MEMBRO_EQUIPE>(entity =>
        {
            entity.HasKey(e => new { e.MeqCodigoMembro, e.MeqCodigoEquipe }).HasName("PK__MEMBRO_E__A9DE3AAFCF9F95F3");

            entity.HasIndex(e => e.MeqCodigoEquipe, "MEMBRO_EQUIPE_FKIndex1");

            entity.HasIndex(e => e.MeqCodigoMembro, "MEMBRO_EQUIPE_FKIndex2");

            entity.Property(e => e.MeqDataRegistro).HasColumnType("datetime");
            entity.Property(e => e.MeqFuncao)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.MeqCodigoEquipeNavigation).WithMany(p => p.MEMBRO_EQUIPE)
                .HasForeignKey(d => d.MeqCodigoEquipe)
                .HasConstraintName("FK__MEMBRO_EQ__MeqCo__45F365D3");

            entity.HasOne(d => d.MeqCodigoMembroNavigation).WithMany(p => p.MEMBRO_EQUIPE)
                .HasForeignKey(d => d.MeqCodigoMembro)
                .HasConstraintName("FK__MEMBRO_EQ__MeqCo__46E78A0C");
        });

        modelBuilder.Entity<PROJETO>(entity =>
        {
            entity.HasKey(e => e.ProCodigo).HasName("PK__PROJETO__90746C2261870A42");

            entity.Property(e => e.ProDataFinal).HasColumnType("datetime");
            entity.Property(e => e.ProDataInicio).HasColumnType("datetime");
            entity.Property(e => e.ProNome)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TAREFA>(entity =>
        {
            entity.HasKey(e => e.TarCodigo).HasName("PK__TAREFA__B889E929B17CFD91");

            entity.Property(e => e.TarDataFinal).HasColumnType("datetime");
            entity.Property(e => e.TarDataInicio).HasColumnType("datetime");
            entity.Property(e => e.TarDescricao)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.TarNome)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.TarCodigoProjetoNavigation).WithMany(p => p.TAREFA)
                .HasForeignKey(d => d.TarCodigoProjeto)
                .HasConstraintName("FK__TAREFA__TarCodig__3D5E1FD2");
        });

        modelBuilder.Entity<TIPO_PROJETO>(entity =>
        {
            entity.HasKey(e => e.TpPCodigo).HasName("PK__TIPO_PRO__A9B7F325810A34AD");

            entity.Property(e => e.TpPDescricao)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.TpPCodigoProjetoNavigation).WithMany(p => p.TIPO_PROJETO)
                .HasForeignKey(d => d.TpPCodigoProjeto)
                .HasConstraintName("FK__TIPO_PROJ__TpPCo__4316F928");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}