// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gerenciador_De_Projetos.MODEL.Models;

public partial class MEMBRO_EQUIPE
{
    public int MeqCodigoMembro { get; set; }

    public int MeqCodigoEquipe { get; set; }

    public string MeqFuncao { get; set; }

    public DateTime MeqDataRegistro { get; set; }

    public virtual EQUIPE MeqCodigoEquipeNavigation { get; set; }

    public virtual MEMBROS MeqCodigoMembroNavigation { get; set; }
}