// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gerenciador_De_Projetos.MODEL.Models;

public partial class MEMBROS
{
    public int MemCodigo { get; set; }

    public string MemNome { get; set; }

    public string MemSexo { get; set; }

    public string MemCPF { get; set; }

    public string MemEmail { get; set; }

    public string MemTelefone { get; set; }

    public DateTime MemDataNascimento { get; set; }

    public virtual ICollection<ENDERECO> ENDERECO { get; set; } = new List<ENDERECO>();

    public virtual ICollection<MEMBRO_EQUIPE> MEMBRO_EQUIPE { get; set; } = new List<MEMBRO_EQUIPE>();
}