// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gerenciador_De_Projetos.MODEL.Models;

public partial class PROJETO
{
    public int ProCodigo { get; set; }

    public string ProNome { get; set; }

    public bool ProStatus { get; set; }

    public DateTime ProDataInicio { get; set; }

    public DateTime? ProDataFinal { get; set; }

    public virtual ICollection<EQUIPE> EQUIPE { get; set; } = new List<EQUIPE>();

    public virtual ICollection<TAREFA> TAREFA { get; set; } = new List<TAREFA>();

    public virtual ICollection<TIPO_PROJETO> TIPO_PROJETO { get; set; } = new List<TIPO_PROJETO>();
}