// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gerenciador_De_Projetos.MODEL.Models;

public partial class PROJETO
{
    public int ProjCodigo { get; set; }

    public int TpPCodigo { get; set; }

    public int TarCodigo { get; set; }

    public int EqpCodigo { get; set; }

    public string ProjNome { get; set; }

    public bool ProStatus { get; set; }

    public DateTime ProDataInicio { get; set; }

    public DateTime? ProDataFinal { get; set; }

    public virtual EQUIPE EqpCodigoNavigation { get; set; }

    public virtual TAREFA TarCodigoNavigation { get; set; }

    public virtual TIPO_PROJETO TpPCodigoNavigation { get; set; }
}