// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gerenciador_De_Projetos.MODEL.Models;

public partial class TIPO_PROJETO
{
    public int TpPCodigo { get; set; }

    public int TpPCodigoProjeto { get; set; }

    public string TpPDescricao { get; set; }

    public virtual PROJETO TpPCodigoProjetoNavigation { get; set; }
}